services:
  grobid:
    image: lfoppiano/grobid:0.8.1  # different than production, works on a mac
    container_name: grobid
    ports:
      - "8070:8070"
    platform: linux/amd64
    environment:
      - JAVA_OPTS="-XX:-UseContainerSupport"
    deploy:
      resources:
        limits:
          memory: 4G

  flask:
    build:
      context: .
      dockerfile: ./Dockerfile
      platforms:
        - linux/amd64
    container_name: flask
    ports:
      - "8080:8080"
    depends_on:
      - grobid
    env_file:
      - .env
